services:
  - type: web
    name: baidu-search-screenshot
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
